"""ReportService -- Sprint 5 STEP 5 (LOCKED DECISION).

``ReportService`` is a pure adapter, nothing more: it turns a
``List[Recommendation]`` (``Business.recommendation_service.
RecommendationService.build_recommendations()``'s output) into a
single ``Report`` in memory. No persistence, no export, no output to
the user, no CLI, no scheduler, no database, no integration -- exactly
the same pattern as ``Business.ranking_engine.RankingEngine`` (STEP 2)
and ``Business.recommendation_service.RecommendationService`` (STEP 4).

Explicitly out of scope for this STEP (LOCKED DECISION): no sort, no
ranking, no filter, no score, no group, no additional copying beyond
the three locked fields, no AI summary, no statistics, no IO, no
database, no repository, no tool, no pipeline, no scheduler, no
Telegram, no Discord, no PDF, no Excel, no JSON, no HTML.

Constructor (LOCKED): ``ReportService()`` -- no dependency whatsoever.
All data arrives through ``build_report()``'s own parameters.

Public API (LOCKED): exactly one public method, ``build_report()``.

``generated_at`` is a required, caller-supplied value -- this service
does not generate a timestamp itself (no ``datetime.now()`` or
equivalent anywhere in this module).

Knowledge boundary (LOCKED): this module imports only
``dataclasses.dataclass`` and ``typing``, plus
``Business.recommendation_service.Recommendation`` for the input type
annotation only (never constructed here). It does NOT import
``Repository.*``, ``Database.*``, any Skill, any Tool, any Pipeline,
any scheduler, or any export/notification module (PDF/Excel/HTML/
JSON/Telegram/Discord).

Not wired to ``Core.composition_root`` (LOCKED DECISION): this STEP
adds no ``ApplicationGraph`` field and no ``_build_*`` function --
``ReportService`` is not a singleton and is not part of the production
object graph, not yet used by any other service, same scope decision
as STEP 4's ``RecommendationService``.

Exception handling: no ``try``/``except`` anywhere in this module, and
no new exception type is defined, mirroring STEP 4. Malformed input
surfaces whatever error Python itself raises, unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

from Business.recommendation_service import Recommendation


@dataclass
class Report:
    """An in-memory report over a list of already-built
    ``Recommendation`` objects.

    Exactly three fields (LOCKED) -- no summary, no best/worst symbol,
    no statistics, no success rate, no field of any kind beyond these
    three.

    Attributes:
        generated_at: Caller-supplied timestamp string identifying
            when this report was generated. Never generated by this
            module itself.
        recommendations: The exact ``List[Recommendation]`` passed to
            ``ReportService.build_report()`` -- same object, same
            order, no re-copy.
        total_symbols: ``len(recommendations)`` at build time.
    """

    generated_at: str
    recommendations: List[Recommendation]
    total_symbols: int


class ReportService:
    """Builds a ``Report`` from a caller-supplied
    ``List[Recommendation]`` and ``generated_at`` timestamp.

    No state, no constructor argument, and no helper method beyond
    ``build_report()`` itself, mirroring
    ``Business.recommendation_service.RecommendationService`` and
    ``Business.ranking_engine.RankingEngine`` exactly.
    """

    def build_report(
        self,
        recommendations: List[Recommendation],
        generated_at: str,
    ) -> Report:
        """Build a ``Report`` over ``recommendations``.

        No sorting, filtering, scoring, grouping, or additional
        copying of any kind is performed -- ``recommendations`` is
        assigned into the ``Report`` as-is (same list object, same
        order, same elements), and ``total_symbols`` is simply
        ``len(recommendations)``. ``generated_at`` is used exactly as
        supplied; this method never generates its own timestamp.

        Args:
            recommendations: The exact list
                ``RecommendationService.build_recommendations()``
                returns (or any list of ``Recommendation``-shaped
                objects).
            generated_at: Caller-supplied timestamp string for this
                report.

        Returns:
            A newly constructed ``Report`` with ``generated_at``,
            ``recommendations``, and ``total_symbols`` set exactly per
            LOCKED DECISION 5.
        """
        return Report(
            generated_at=generated_at,
            recommendations=recommendations,
            total_symbols=len(recommendations),
        )