from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from Core.exceptions import ValidationError
from Database.account_constants import ACCOUNT_ASSET_CLASSES, ACCOUNT_MODES
from Database.models import Account
from Repository.persistence.base_persistence_repository import BasePersistenceRepository


class AccountRepository(BasePersistenceRepository):
    """Persists and queries Accounts -- the root of every portfolio.

    ``account_id`` is a stable, caller-assigned string (e.g.
    ``"paper-id"``, ``"crypto-main"``) -- this repository never
    generates one itself.

    Accounts are MUTABLE: cash/equity/buying_power are updated in
    place via ``update_balances``, not appended as new rows.

    Deliberately has NO ``delete``/``remove``/``delete_account``
    method. Accounts are the root of the entire portfolio and must
    never be permanently removable at this layer -- an archive/
    deactivate mechanism, if ever needed, is a separate future sprint
    decision, not part of Sprint 3.

    ``mode``/``asset_class`` validation reads from
    ``Database.account_constants`` -- the same single source of truth
    the ``accounts`` table's SQL ``CHECK`` constraints are generated
    from (see ``Database.migrations_accounts``). No separate value
    list is defined here.
    """

    def create(
        self,
        account_id: str,
        account_name: str,
        mode: str,
        currency: str,
        asset_class: str,
        cash: float,
        equity: float,
        buying_power: float,
    ) -> Account:
        """Create a new account row.

        Args:
            account_id: Stable, caller-assigned identifier (e.g.
                ``"paper-id"``). Never generated by this repository.
            account_name: Human-readable, unique account name.
            mode: Must be one of ``Database.account_constants.ACCOUNT_MODES``.
            currency: ISO currency code (e.g. ``"IDR"``, ``"USD"``).
            asset_class: Must be one of
                ``Database.account_constants.ACCOUNT_ASSET_CLASSES``.
            cash: Initial cash balance.
            equity: Initial equity value.
            buying_power: Initial buying power.

        Returns:
            The newly created :class:`Database.models.Account`.

        Raises:
            ValidationError: If ``mode`` or ``asset_class`` is outside
                the allowed domain.
            RepositoryError: If ``account_id`` or ``account_name``
                already exists (PRIMARY KEY / UNIQUE violation), or the
                underlying statement fails for any other reason.
        """
        self._validate_mode(mode)
        self._validate_asset_class(asset_class)

        now = datetime.now(timezone.utc).isoformat()
        self._execute(
            """
            INSERT INTO accounts
                (account_id, account_name, mode, currency, asset_class,
                 cash, equity, buying_power, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (account_id, account_name, mode, currency, asset_class,
             cash, equity, buying_power, now, now),
        )
        return Account(
            account_id=account_id,
            account_name=account_name,
            mode=mode,
            currency=currency,
            asset_class=asset_class,
            cash=cash,
            equity=equity,
            buying_power=buying_power,
            created_at=now,
            updated_at=now,
        )

    def get_by_id(self, account_id: str) -> Optional[Account]:
        """Return the account with ``account_id``, or ``None`` if absent.

        Raises:
            RepositoryError: If the underlying statement fails.
        """
        result = self._execute("SELECT * FROM accounts WHERE account_id = ?", (account_id,))
        return self._row_to_account(result.rows[0]) if result.rows else None

    def get_by_name(self, account_name: str) -> Optional[Account]:
        """Return the account with ``account_name``, or ``None`` if absent.

        Raises:
            RepositoryError: If the underlying statement fails.
        """
        result = self._execute("SELECT * FROM accounts WHERE account_name = ?", (account_name,))
        return self._row_to_account(result.rows[0]) if result.rows else None

    def list_all(self) -> List[Account]:
        """Return every account, ordered by ``account_id`` ascending.

        Raises:
            RepositoryError: If the underlying statement fails.
        """
        result = self._execute("SELECT * FROM accounts ORDER BY account_id ASC")
        return [self._row_to_account(row) for row in result.rows]

    def update_balances(
        self, account_id: str, cash: float, equity: float, buying_power: float
    ) -> None:
        """Update cash/equity/buying_power in place, and bump ``updated_at``.

        Mutable update -- not append-only. Silently affects zero rows
        if ``account_id`` does not exist (mirrors
        ``WatchlistRepository.remove``'s tolerant style; callers that
        need existence confirmation should ``get_by_id`` first).

        Raises:
            RepositoryError: If the underlying statement fails.
        """
        updated_at = datetime.now(timezone.utc).isoformat()
        self._execute(
            """
            UPDATE accounts
            SET cash = ?, equity = ?, buying_power = ?, updated_at = ?
            WHERE account_id = ?
            """,
            (cash, equity, buying_power, updated_at, account_id),
        )

    @staticmethod
    def _validate_mode(mode: str) -> None:
        if mode not in ACCOUNT_MODES:
            raise ValidationError(
                f"Invalid mode '{mode}': must be one of {list(ACCOUNT_MODES)}",
                details={"mode": mode},
            )

    @staticmethod
    def _validate_asset_class(asset_class: str) -> None:
        if asset_class not in ACCOUNT_ASSET_CLASSES:
            raise ValidationError(
                f"Invalid asset_class '{asset_class}': must be one of "
                f"{list(ACCOUNT_ASSET_CLASSES)}",
                details={"asset_class": asset_class},
            )

    @staticmethod
    def _row_to_account(row) -> Account:
        return Account(
            account_id=row["account_id"],
            account_name=row["account_name"],
            mode=row["mode"],
            currency=row["currency"],
            asset_class=row["asset_class"],
            cash=row["cash"],
            equity=row["equity"],
            buying_power=row["buying_power"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )
